
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_bell
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9003:9000"
    networks:
      - laravel_network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: laravel_db_bell
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: F11sabilillah!
      MYSQL_DATABASE: pos-db-bell
      MYSQL_USER: userbell
      MYSQL_PASSWORD: F11sabilillah!
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_bell
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"
    networks:
      - laravel_network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_bell
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: F11sabilillah!
    ports:
      - "8086:80"
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
